#
# Makefile for the touchscreen drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_INPUT_TOUCHSCREEN_GT911)          += gt9xx_ts.o
gt9xx_ts-objs := goodix_tool.o gt9xx_update.o gt9xx.o

